window.sportsWords = [
    { word1: "Football", word2: "Basketball" },
    { word1: "Tennis", word2: "Badminton" },
    { word1: "Natation", word2: "Plongée" },
    { word1: "Boxe", word2: "MMA" },
    { word1: "Ski", word2: "Snowboard" },
    { word1: "Athlétisme", word2: "Gymnastique" },
    { word1: "Arbitre", word2: "Entraîneur" },
    { word1: "Médaille", word2: "Trophée" },
    { word1: "Jeux Olympiques", word2: "Coupe du Monde" },
    { word1: "Sprint", word2: "Marathon" },
    { word1: "Rugby", word2: "Football Américain" },
    { word1: "Volley", word2: "Handball" },
    { word1: "Patinage", word2: "Hockey sur glace" },
    { word1: "Golf", word2: "Mini-golf" },
    { word1: "Escalade", word2: "Alpinisme" },
    { word1: "Randonnée", word2: "Trail" },
    { word1: "Formule 1", word2: "MotoGP" },
    { word1: "Musculation", word2: "CrossFit" },
    { word1: "Yoga", word2: "Pilates" },
    { word1: "Equitation", word2: "Poney" },
    { word1: "Cricket", word2: "Baseball" },
    { word1: "Skateboard", word2: "Trottinette freestyle" },
    { word1: "Football", word2: "Futsal" }
];
